# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Boruto\Desktop\Chio\Python\CRUD-Wishlist\forms\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1144, 663)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 523))
        MainWindow.setBaseSize(QtCore.QSize(700, 450))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/if_Preview_131689.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(0)
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(129, 129, 129);")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        MainWindow.setWindowFilePath("")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-image: none;")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1151, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.715909, y1:0.744, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.517045 rgba(129, 129, 129, 255), stop:0.846591 rgba(129, 129, 129, 255));\n"
"font: 50pt \"Impact\";\n"
"color: qlineargradient(spread:pad, x1:0.715909, y1:0.744, x2:1, y2:0, stop:0 rgba(223, 223, 223, 255), stop:0.517045 rgba(189, 189, 189, 255), stop:0.846591 rgba(212, 212, 212, 255));")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.InformationBox = QtWidgets.QGroupBox(self.centralwidget)
        self.InformationBox.setGeometry(QtCore.QRect(350, 100, 701, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InformationBox.sizePolicy().hasHeightForWidth())
        self.InformationBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.InformationBox.setFont(font)
        self.InformationBox.setToolTip("")
        self.InformationBox.setTitle("")
        self.InformationBox.setFlat(True)
        self.InformationBox.setObjectName("InformationBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.InformationBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImageLayots = QtWidgets.QGroupBox(self.InformationBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLayots.sizePolicy().hasHeightForWidth())
        self.ImageLayots.setSizePolicy(sizePolicy)
        self.ImageLayots.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.ImageLayots.setTitle("")
        self.ImageLayots.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.ImageLayots.setFlat(True)
        self.ImageLayots.setCheckable(False)
        self.ImageLayots.setObjectName("ImageLayots")
        self.ImageLayout = QtWidgets.QHBoxLayout(self.ImageLayots)
        self.ImageLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ImageLayout.setContentsMargins(0, 0, 0, 0)
        self.ImageLayout.setSpacing(0)
        self.ImageLayout.setObjectName("ImageLayout")
        self.ImageName = QtWidgets.QLabel(self.ImageLayots)
        self.ImageName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageName.sizePolicy().hasHeightForWidth())
        self.ImageName.setSizePolicy(sizePolicy)
        self.ImageName.setMinimumSize(QtCore.QSize(150, 250))
        self.ImageName.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.ImageName.setFont(font)
        self.ImageName.setTabletTracking(False)
        self.ImageName.setAcceptDrops(False)
        self.ImageName.setStatusTip("")
        self.ImageName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ImageName.setAutoFillBackground(False)
        self.ImageName.setStyleSheet("text-decoration: underline;")
        self.ImageName.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ImageName.setMidLineWidth(0)
        self.ImageName.setScaledContents(False)
        self.ImageName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImageName.setWordWrap(True)
        self.ImageName.setOpenExternalLinks(False)
        self.ImageName.setObjectName("ImageName")
        self.ImageLayout.addWidget(self.ImageName)
        self.widget_2 = QtWidgets.QWidget(self.ImageLayots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.NameLabel_4 = QtWidgets.QLabel(self.widget_2)
        self.NameLabel_4.setGeometry(QtCore.QRect(130, 20, 300, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameLabel_4.sizePolicy().hasHeightForWidth())
        self.NameLabel_4.setSizePolicy(sizePolicy)
        self.NameLabel_4.setMinimumSize(QtCore.QSize(220, 220))
        self.NameLabel_4.setMaximumSize(QtCore.QSize(300, 300))
        self.NameLabel_4.setAutoFillBackground(False)
        self.NameLabel_4.setStyleSheet("color: rgb(229, 229, 229);\n"
"background-color: rgb(62, 62, 62);")
        self.NameLabel_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.NameLabel_4.setLineWidth(2)
        self.NameLabel_4.setScaledContents(False)
        self.NameLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel_4.setWordWrap(False)
        self.NameLabel_4.setIndent(1)
        self.NameLabel_4.setObjectName("NameLabel_4")
        self.ImageLayout.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.ImageLayots)
        self.NameWidget = QtWidgets.QWidget(self.InformationBox)
        self.NameWidget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.NameWidget.setObjectName("NameWidget")
        self.NameLayout = QtWidgets.QHBoxLayout(self.NameWidget)
        self.NameLayout.setObjectName("NameLayout")
        self.PreNameLabel = QtWidgets.QLabel(self.NameWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreNameLabel.sizePolicy().hasHeightForWidth())
        self.PreNameLabel.setSizePolicy(sizePolicy)
        self.PreNameLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.PreNameLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.PreNameLabel.setFont(font)
        self.PreNameLabel.setAcceptDrops(False)
        self.PreNameLabel.setAutoFillBackground(False)
        self.PreNameLabel.setStyleSheet("text-decoration: underline;")
        self.PreNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PreNameLabel.setWordWrap(True)
        self.PreNameLabel.setObjectName("PreNameLabel")
        self.NameLayout.addWidget(self.PreNameLabel)
        self.NameLabel = QtWidgets.QLabel(self.NameWidget)
        self.NameLabel.setAutoFillBackground(False)
        self.NameLabel.setWordWrap(True)
        self.NameLabel.setObjectName("NameLabel")
        self.NameLayout.addWidget(self.NameLabel)
        self.verticalLayout_2.addWidget(self.NameWidget)
        self.PriceWidget = QtWidgets.QWidget(self.InformationBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceWidget.sizePolicy().hasHeightForWidth())
        self.PriceWidget.setSizePolicy(sizePolicy)
        self.PriceWidget.setMaximumSize(QtCore.QSize(16777215, 85))
        self.PriceWidget.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.PriceWidget.setObjectName("PriceWidget")
        self.PriceLayout = QtWidgets.QHBoxLayout(self.PriceWidget)
        self.PriceLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.PriceLayout.setSpacing(6)
        self.PriceLayout.setObjectName("PriceLayout")
        self.PriceLabel = QtWidgets.QLabel(self.PriceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceLabel.sizePolicy().hasHeightForWidth())
        self.PriceLabel.setSizePolicy(sizePolicy)
        self.PriceLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.PriceLabel.setMaximumSize(QtCore.QSize(150, 85))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.PriceLabel.setFont(font)
        self.PriceLabel.setAcceptDrops(False)
        self.PriceLabel.setAutoFillBackground(False)
        self.PriceLabel.setStyleSheet("text-decoration: underline;")
        self.PriceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PriceLabel.setWordWrap(True)
        self.PriceLabel.setObjectName("PriceLabel")
        self.PriceLayout.addWidget(self.PriceLabel)
        self.PriceNumber = QtWidgets.QLCDNumber(self.PriceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceNumber.sizePolicy().hasHeightForWidth())
        self.PriceNumber.setSizePolicy(sizePolicy)
        self.PriceNumber.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PriceNumber.setFont(font)
        self.PriceNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PriceNumber.setAutoFillBackground(False)
        self.PriceNumber.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.PriceNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PriceNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PriceNumber.setLineWidth(0)
        self.PriceNumber.setSmallDecimalPoint(False)
        self.PriceNumber.setDigitCount(15)
        self.PriceNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.PriceNumber.setProperty("value", 199.99)
        self.PriceNumber.setObjectName("PriceNumber")
        self.PriceLayout.addWidget(self.PriceNumber)
        self.label_3 = QtWidgets.QLabel(self.PriceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setTabletTracking(False)
        self.label_3.setAcceptDrops(False)
        self.label_3.setToolTip("")
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.PriceLayout.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.PriceWidget)
        self.LinkWidget = QtWidgets.QWidget(self.InformationBox)
        self.LinkWidget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.LinkWidget.setObjectName("LinkWidget")
        self.NameLayout_2 = QtWidgets.QHBoxLayout(self.LinkWidget)
        self.NameLayout_2.setObjectName("NameLayout_2")
        self.PreNameLabel_2 = QtWidgets.QLabel(self.LinkWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreNameLabel_2.sizePolicy().hasHeightForWidth())
        self.PreNameLabel_2.setSizePolicy(sizePolicy)
        self.PreNameLabel_2.setMinimumSize(QtCore.QSize(150, 0))
        self.PreNameLabel_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.PreNameLabel_2.setFont(font)
        self.PreNameLabel_2.setAcceptDrops(False)
        self.PreNameLabel_2.setAutoFillBackground(False)
        self.PreNameLabel_2.setStyleSheet("text-decoration: underline;")
        self.PreNameLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PreNameLabel_2.setWordWrap(True)
        self.PreNameLabel_2.setObjectName("PreNameLabel_2")
        self.NameLayout_2.addWidget(self.PreNameLabel_2)
        self.NameLabel_2 = QtWidgets.QLabel(self.LinkWidget)
        self.NameLabel_2.setAutoFillBackground(False)
        self.NameLabel_2.setWordWrap(True)
        self.NameLabel_2.setOpenExternalLinks(True)
        self.NameLabel_2.setObjectName("NameLabel_2")
        self.NameLayout_2.addWidget(self.NameLabel_2)
        self.verticalLayout_2.addWidget(self.LinkWidget)
        self.EntryLabel = QtWidgets.QWidget(self.InformationBox)
        self.EntryLabel.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.EntryLabel.setObjectName("EntryLabel")
        self.NoteLayout = QtWidgets.QHBoxLayout(self.EntryLabel)
        self.NoteLayout.setObjectName("NoteLayout")
        self.NoteText = QtWidgets.QLabel(self.EntryLabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoteText.sizePolicy().hasHeightForWidth())
        self.NoteText.setSizePolicy(sizePolicy)
        self.NoteText.setMinimumSize(QtCore.QSize(150, 0))
        self.NoteText.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.NoteText.setFont(font)
        self.NoteText.setAcceptDrops(False)
        self.NoteText.setAutoFillBackground(False)
        self.NoteText.setStyleSheet("text-decoration: underline;")
        self.NoteText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.NoteText.setWordWrap(True)
        self.NoteText.setObjectName("NoteText")
        self.NoteLayout.addWidget(self.NoteText)
        self.NoteLabel = QtWidgets.QLabel(self.EntryLabel)
        self.NoteLabel.setAutoFillBackground(False)
        self.NoteLabel.setWordWrap(True)
        self.NoteLabel.setObjectName("NoteLabel")
        self.NoteLayout.addWidget(self.NoteLabel)
        self.verticalLayout_2.addWidget(self.EntryLabel)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 100, 211, 521))
        self.widget.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(170, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ButtonsWidget = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonsWidget.sizePolicy().hasHeightForWidth())
        self.ButtonsWidget.setSizePolicy(sizePolicy)
        self.ButtonsWidget.setObjectName("ButtonsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonsWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddButton = QtWidgets.QPushButton(self.ButtonsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setMinimumSize(QtCore.QSize(40, 40))
        self.AddButton.setMaximumSize(QtCore.QSize(4040, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/if_Add_131846.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddButton.setIcon(icon1)
        self.AddButton.setIconSize(QtCore.QSize(32, 32))
        self.AddButton.setAutoDefault(False)
        self.AddButton.setDefault(False)
        self.AddButton.setFlat(True)
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout.addWidget(self.AddButton)
        self.EditButton = QtWidgets.QPushButton(self.ButtonsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditButton.sizePolicy().hasHeightForWidth())
        self.EditButton.setSizePolicy(sizePolicy)
        self.EditButton.setMinimumSize(QtCore.QSize(40, 40))
        self.EditButton.setMaximumSize(QtCore.QSize(4040, 40))
        self.EditButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/if_Pencil_131733.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditButton.setIcon(icon2)
        self.EditButton.setIconSize(QtCore.QSize(32, 32))
        self.EditButton.setAutoDefault(False)
        self.EditButton.setDefault(False)
        self.EditButton.setFlat(True)
        self.EditButton.setObjectName("EditButton")
        self.horizontalLayout.addWidget(self.EditButton)
        self.DeleteButton = QtWidgets.QPushButton(self.ButtonsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        self.DeleteButton.setMinimumSize(QtCore.QSize(40, 40))
        self.DeleteButton.setMaximumSize(QtCore.QSize(4040, 40))
        font = QtGui.QFont()
        self.DeleteButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/if_Cancel_131742.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon3)
        self.DeleteButton.setIconSize(QtCore.QSize(32, 32))
        self.DeleteButton.setAutoRepeatInterval(100)
        self.DeleteButton.setAutoDefault(False)
        self.DeleteButton.setDefault(False)
        self.DeleteButton.setFlat(True)
        self.DeleteButton.setObjectName("DeleteButton")
        self.horizontalLayout.addWidget(self.DeleteButton)
        self.verticalLayout.addWidget(self.ButtonsWidget)
        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMinimumSize(QtCore.QSize(170, 0))
        self.listView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listView.setAutoFillBackground(True)
        self.listView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setDragEnabled(True)
        self.listView.setDragDropOverwriteMode(False)
        self.listView.setAlternatingRowColors(True)
        self.listView.setTextElideMode(QtCore.Qt.ElideRight)
        self.listView.setMovement(QtWidgets.QListView.Free)
        self.listView.setFlow(QtWidgets.QListView.TopToBottom)
        self.listView.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView.setUniformItemSizes(False)
        self.listView.setWordWrap(False)
        self.listView.setSelectionRectVisible(False)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.EditButton, self.DeleteButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wishlist"))
        self.label_2.setText(_translate("MainWindow", "С П И С О К      Ж Е Л А Н И Й"))
        self.ImageName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Изображение:</span></p></body></html>"))
        self.NameLabel_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">НЕТ ФОТО</span></p></body></html>"))
        self.PreNameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Наименование:</span></p></body></html>"))
        self.NameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Большая банка солёных огурцов к кислосладком соусе</span></p></body></html>"))
        self.PriceLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Цена:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Р"))
        self.PreNameLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Ссылка:</span></p></body></html>"))
        self.NameLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.farpost.ru/vladivostok/food/organic/ogurcy-malosolnye-57356470.html\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.farpost.ru/vladivostok/food/organic/ogurcy-malosolnye-57356470.html</span></a></p></body></html>"))
        self.NoteText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Примечание:</span></p></body></html>"))
        self.NoteLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Большая банка солёных огурцов к кислосладком соусе</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Элементы управления</span></p></body></html>"))
        self.AddButton.setToolTip(_translate("MainWindow", "Добавить новый элемент"))
        self.EditButton.setToolTip(_translate("MainWindow", "Редактировать элемент (ВНИМАНИЕ: Должна быть выбрана строка для редактирования)"))
        self.DeleteButton.setToolTip(_translate("MainWindow", "Удалить элемент (ВНИМАНИЕ: должна быть выбрана строка для удаления)"))
        self.listView.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ваш список желаний. Щелкните по пункту, чтобы узнать подробнее.</p></body></html>"))

import resources_rc
